version: '3.8'

services:
  # Main Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - database
      - redis
    networks:
      - laravel-network

  # Web Server
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  # Database
  database:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: musamin
      MYSQL_USER: musamin_user
      MYSQL_PASSWORD: Musamin@70
      MYSQL_ROOT_PASSWORD: Musamin@70
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

  # Redis for Cache, Sessions, Queues, Reverb
  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    networks:
      - laravel-network

  # Queue Worker
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    depends_on:
      - app
      - database
      - redis
    networks:
      - laravel-network

  # Laravel Reverb (WebSockets)
  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-reverb
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    depends_on:
      - app
      - redis
    networks:
      - laravel-network

volumes:
  dbdata:
  redisdata:

networks:
  laravel-network:
    driver: bridge