version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musamin-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_DATABASE=musamin1
      - DB_USERNAME=musamin
      - DB_PASSWORD=musamin_password
      - REDIS_HOST=redis
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - db
      - redis
    networks:
      - musamin-network

  nginx:
    image: nginx:alpine
    container_name: musamin-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - musamin-network

  db:
    image: mysql:8.0
    container_name: musamin-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: musamin1
      MYSQL_USER: musamin
      MYSQL_PASSWORD: musamin_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - musamin-network

  redis:
    image: redis:7-alpine
    container_name: musamin-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - musamin-network

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musamin-reverb
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_DATABASE=musamin1
      - DB_USERNAME=musamin
      - DB_PASSWORD=musamin_password
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - musamin-network

volumes:
  db_data:
  redis_data:

networks:
  musamin-network:
    driver: bridge