version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musamin-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app_storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - REDIS_HOST=redis
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - redis
    networks:
      - musamin-network
      - coolify
    expose:
      - "9000"

  redis:
    image: redis:7-alpine
    container_name: musamin-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - musamin-network
      - coolify

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musamin-reverb
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    expose:
      - "8080"
    volumes:
      - app_storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - musamin-network
      - coolify

volumes:
  redis_data:
  app_storage:

networks:
  musamin-network:
    driver: bridge
  coolify:
    external: true