version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_DEBUG=${APP_DEBUG}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_NAME=${APP_NAME}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - MAIL_MAILER=${MAIL_MAILER}
      - HASHIDS_ALT_SALT=${HASHIDS_ALT_SALT}
      - HASHIDS_SALT=${HASHIDS_SALT}