version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musamin-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - REDIS_HOST=redis
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - redis
    networks:
      - musamin-network
    ports:
      - "8081:9000"

  redis:
    image: redis:7-alpine
    container_name: musamin-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - musamin-network

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musamin-reverb
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8082:8080"
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=production
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - musamin-network

volumes:
  redis_data:

networks:
  musamin-network:
    driver: bridge